### ISSUE TITLE
Got this error while running it on ubuntu vps

### ISSUE THREAD

**Issue by beast076** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#122]
[WDM] - Current google-chrome version is 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - There is no [linux64] chromedriver for browser 87.0.4280 in cache
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
[WDM] - Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/87.0.4280.20]
Traceback (most recent call last):
  File "udemy_enroller_chrome.py", line 29, in <module>
    driver = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by fakeid30** [comment]
@beast076 we don't support running it on vps since the vps OS doesn't have the same libraries as a desktop. you might find better luck on an rdp if you really can't use desktop.

**Comment by Brblol** [comment]
I'm getting the same issue on my ubuntu machine not VPS @fakeid30 

```
m:~/playground/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE$ python3 udemy_enroller.py --browser=chromium
Loading existing settings
 
[WDM] - Current chromium version is 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Driver [/home/m/.wdm/drivers/chromedriver/linux64/87.0.4280.88/chromedriver] found in cache
Traceback (most recent call last):
  File "udemy_enroller.py", line 77, in <module>
    run(args.browser, args.max_pages, args.cache_hits)
  File "udemy_enroller.py", line 31, in run
    dm = DriverManager(browser=browser, is_ci_build=settings.is_ci_build)
  File "/home/m/playground/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/driver_manager.py", line 37, in __init__
    self._init_driver()
  File "/home/m/playground/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/driver_manager.py", line 53, in _init_driver
    self.driver = webdriver.Chrome(
  File "/home/m/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/m/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/m/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/m/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/m/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

```

**Comment by fakeid30** [comment]
@Brblol can you try the command with : 

`--max-pages=12 --cache-hits=12`

If that doesn't work, can you try the develop branch?
