### ISSUE TITLE
[BUG] Missing webdriver_manager

### ISSUE THREAD

**Issue by RocketNinja15** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#165]
**Describe the bug**
Trying to launch results in a webdriver_manager
**To Reproduce**
1. Install Chrome WebDriver
2. Launch it
3. then do python3 udemy_enroller_chrome.py

**Expected behavior**
It to launch
**Desktop (please complete the following information):**
 - OS: [e.g. Arch Linux]
MacOS, Chrome
**Additional context**

```
REE name$ udemy_enroller_chromium.py
-bash: udemy_enroller_chromium.py: command not found
Carters-MacBook-Air:Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE name$ python3 udemy_enroller_chromium.py
Traceback (most recent call last):
  File "/Users/name/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller_chromium.py", line 6, in <module>
    from udemy_enroller import parse_args, run
  File "/Users/name/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller.py", line 10, in <module>
    from core import ALL_VALID_BROWSER_STRINGS, DriverManager, Settings
  File "/Users/name/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/__init__.py", line 4, in <module>
    from .driver_manager import ALL_VALID_BROWSER_STRINGS, DriverManager
  File "/Users/name/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/driver_manager.py", line 5, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'
```

**Comment by fakeid30** [comment]
You did not install the requirements. Install them from requirements.txt then run the file again.

**Comment by fakeid30** [comment]
If you have any further issue post a comment here.
