### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by manafn** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#268]
Hello, I felt I have to report this, is it normal to recheck links?  or it should remove the duplicate links + I got an error but didn't affect the process  

look for TikTok course and maybe there is more

```
Loading existing settings
Loading cookies from file
Loading existing course details
Currently enrolled in 2247 courses
tutorialbar scraper is running
discudemy scraper is running
coursevania scraper is running
Page: 1 of 178 scraped from coursevania.com
Got 12 links from https://coursevania.com in 19.51 seconds
Page: 1 of 823 scraped from tutorialbar.com
Page: 1 of 494 scraped from discudemy.com
Got 14 links from https://discudemy.com in 19.59 seconds
Removing ad links from courses: {'https://bit.ly/3mkKui2'}
Got 11 links from https://www.tutorialbar.com in 22.19 seconds
Already enrolled in: Front End Web Development Ultimate Course 2021
Already enrolled in: AutoCAD para MAC
Already enrolled in: Applied Linux Command Line and Shell Scripting Zero to Elite
Already enrolled in: G Suite Master Course
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Manaf\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Manaf\AppData\Local\Programs\Python\Python37\lib\encodings\cp1256.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xa1' in position 105: character maps to <undefined>
Call stack:
  File "C:\Users\Manaf\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\udemy_enroller.py", line 4, in <module>
    main()
  File "C:\Users\Manaf\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\udemy_enroller\cli.py", line 130, in main
    args.delete_settings,
  File "C:\Users\Manaf\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\udemy_enroller\cli.py", line 60, in run
    settings, tutorialbar_enabled, discudemy_enabled, coursevania_enabled, max_pages
  File "C:\Users\Manaf\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\udemy_enroller\runner.py", line 77, in redeem_courses
    _redeem_courses(settings, scrapers)
  File "C:\Users\Manaf\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\udemy_enroller\runner.py", line 33, in _redeem_courses
    status = udemy_actions.enroll(course_link)
  File "C:\Users\Manaf\Desktop\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\udemy_enroller\udemy.py", line 296, in enroll
    logger.info(f"Already enrolled in: {course_identifier}")
Message: 'Already enrolled in: Curso de Adobe Photoshop. ¡Desde iniciación a experto!'
Arguments: ()
Already enrolled in: Curso de Adobe Photoshop. ¡Desde iniciación a experto!
Already enrolled in: Adobe Premiere Pro CC Essential Video Editing Zero To Hero
Successfully enrolled: Docker Certified Associate (DCA) Practice Test
Already enrolled in: Lightroom CC Masterclass | Beginner guide for Photographers!
Already enrolled in: Dropshipping with Shopify | Selling Online Worldwide
Already enrolled in: Practical Cisco Networking Labs in Cisco Packet Tracer
Already enrolled in: Microsoft Office 365 Master Course
Already enrolled in: SEO TRAINING 2021: Complete SEO Course + WordPress SEO Yoast
Already enrolled in: Applied Linux Command Line and Shell Scripting Zero to Elite
Already enrolled in: Infographics to tell a story
Already enrolled in: Lightroom CC Masterclass | Beginner guide for Photographers!
Already enrolled in: Python Complete Course For Python Beginners
Already enrolled in: Adobe Premiere Pro CC Essential Video Editing Zero To Hero
Already enrolled in: Machine Learning & Deep Learning in Python & R
Already enrolled in: Python And Flask Framework Complete Course
Already enrolled in: Python Bootcamp 2021 Build 15 working Applications and Games
Already enrolled in: Adobe Illustrator CC 2021: Essential Graphic Design Training
Already enrolled in: TikTok for Business: a Shortcut to Profit from TikTok
Already enrolled in: HTML 5 from Beginner to Pro-Code [ 7 Days Challange ]
Already enrolled in: Lightroom CC Masterclass | Beginner guide for Photographers!
Successfully enrolled: Python for Data Science and Machine Learning
Already enrolled in: Adobe Illustrator CC 2021: Essential Graphic Design Training
Already enrolled in: Technical Analysis Mastery: Stock Trading, Forex , Investing
Already enrolled in: Business Analytics with R 2021
Already enrolled in: Applied Linux Command Line and Shell Scripting Zero to Elite
Already enrolled in: GET on TOP of Real Estate Business with Facebook Ads in 2021
Successfully enrolled: Product Management: Build an Effective Digital Product
Already enrolled in: Complete JAVASCRIPT with HTML5,CSS3 from zero to Expert-2021
Already enrolled in: Video Editing with Adobe Premiere Pro CC 2021 for Beginners
tutorialbar scraper is running
discudemy scraper is running
coursevania scraper is running
Page: 2 of 823 scraped from tutorialbar.com
Page: 2 of 178 scraped from coursevania.com
Got 12 links from https://coursevania.com in 4.27 seconds
Got 12 links from https://www.tutorialbar.com in 4.28 seconds
Page: 2 of 494 scraped from discudemy.com
Got 9 links from https://discudemy.com in 5.32 seconds
Successfully enrolled: CSS3 and Bootstrap for Absolute Beginners : 4 courses in 1
Successfully enrolled: Color Grading and Video Editing with Davinci Resolve 17
Already enrolled in: Make Money From Home: 10 EASY Options to Make Money Now
Successfully enrolled: Bookkeeping in QuickBooks Online (Bookkeeping & accounting)
Successfully enrolled: Amazon FBA Mastery Course - How to Sell on Amazon
Already enrolled in: SEO TRAINING 2021: Complete SEO Course + WordPress SEO Yoast
Already enrolled in: Learn Economics from scratch, ECO04
Already enrolled in: The Complete Oracle SQL Development Bootcamp 2021
Successfully enrolled: Active Directory Administration for Helpdesk Technicians
Already enrolled in: Setup Global Trade Online Instantly | From Anywhere, Anytime
Already enrolled in: Setup Global Trade Online Instantly | From Anywhere, Anytime
Successfully enrolled: Complete Shopify For Beginners Blueprint
Successfully enrolled: BEST of SEO: #1 SEO Training & Content Marketing Course 2021
Successfully enrolled: Complete Video Game Music Composition & Music Theory Secrets
Already enrolled in: Data Engineering Essentials - SQL, Python and Spark
Successfully enrolled: Complete Spanish Course: Learn Spanish for Beginners
Already enrolled in: The Complete Oracle SQL Development Bootcamp 2021
Already enrolled in: Web Development Masterclass - Complete Certificate Course
Already enrolled in: Learn Artificial Neural Network From Scratch in Python
Already enrolled in: Learn Adobe Animate from Scratch
Already enrolled in: Data Engineering Essentials - SQL, Python and Spark
Already enrolled in: Python Bootcamp 2021 Build 15 working Applications and Games
Already enrolled in: SEO TRAINING 2021: Complete SEO Course + WordPress SEO Yoast
Already enrolled in: BEST of SEO: #1 SEO Training & Content Marketing Course 2021
Already enrolled in: Facebook Traffic Mastrclass:Free Facebook Traffic Strategies
Already enrolled in: Bootstrap From Scratch - Fast and Responsive Web Development
Already enrolled in: IP Addressing and Subnetting - Zero to Hero
Already enrolled in: Complete Introduction into Video Creation & Video Marketing
tutorialbar scraper is running
discudemy scraper is running
coursevania scraper is running
Page: 3 of 823 scraped from tutorialbar.com
Page: 3 of 178 scraped from coursevania.com
Got 12 links from https://coursevania.com in 4.03 seconds
Removing ad links from courses: {'https://bit.ly/39I2nSJ'}
Got 11 links from https://www.tutorialbar.com in 4.04 seconds
Page: 3 of 494 scraped from discudemy.com
Got 3 links from https://discudemy.com in 4.56 seconds
Already enrolled in: Adobe Illustrator CC 2021: Essential Graphic Design Training
Already enrolled in: Facebook Traffic Mastrclass:Free Facebook Traffic Strategies
Successfully enrolled: Beginners Forex Trading : Forex Trading Crash Course
Already enrolled in: Microsoft Excel -Basic Excel/ Advanced Excel Formulas
Already enrolled in: TikTok for Business: a Shortcut to Profit from TikTok
Already enrolled in: Becoming A Sales Professional
Already enrolled in: Technical Analysis Mastery: Stock Trading, Forex , Investing
Already enrolled in: AWS Certified Cloud Practitioner - Practice Test 2021 [new]
Already enrolled in: AWS Certified Developer Associate [DVA-C01] Test Exam 2021
```

**Comment by fakeid30** [comment]
@manafn thanks for the issue. Yes links are checked multiple times because of how the algorithm is set up. You can send a PR for this behaviour to change. You can message me personally if you need pointer on how to do that. 

The issue you are facing is completely normal, this doesn't affect the usability of the product, right? I am closing this issue since it's a non issue.
