### ISSUE TITLE
[BUG] collab doest work

### ISSUE THREAD

**Issue by adarsh-goel** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#375]
**Describe the bug**
Trying to login
Login Error
Traceback (most recent call last):
  File "<ipython-input-1-b8ef94d8895b>", line 577, in <module>
    head, user, currency, s= check_login()
  File "<ipython-input-1-b8ef94d8895b>", line 353, in check_login
    csrf_token = soup.find("input", {"name": "csrfmiddlewaretoken"})["value"]
TypeError: 'NoneType' object is not subscriptable

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-b8ef94d8895b>", line 180, in coursevania
    nonce = json.loads([script.string for script in soup.find_all('script') if script.string and "load_content" in script.string][0].strip("_mlv = norsecat;\n"))["load_content"]
IndexError: list index out of range

Tutorial Bar:   8%|▊         | 3/36 [00:00<00:10,  3.08it/s]Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-b8ef94d8895b>", line 231, in enext
    big_all = soup.find("div", {"class": "scroll-box"}).find_all("p", {"class": "p2"})
AttributeError: 'NoneType' object has no attribute 'find_all'

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-b8ef94d8895b>", line 87, in discudemy
    url = item["href"].split("/")[4]
  File "/usr/local/lib/python3.7/dist-packages/bs4/element.py", line 1071, in __getitem__
    return self.attrs[key]
KeyError: 'href'

Discudemy:   2%|▏         | 1/48 [00:00<00:00, 107.30it/s]
IDownloadCoupons: 100%|██████████| 45/45 [00:00<00:00, 17631.36it/s]
Tutorial Bar: 100%|██████████| 36/36 [00:08<00:00,  4.12it/s]
Real Discount: 100%|██████████| 24/24 [00:13<00:00,  1.72it/s]
Udemy Freebies: 100%|██████████| 24/24 [00:34<00:00,  1.43s/it]
0 Python for Machine Learning: The Complete Beginner's Course https://www.udemy.com/course/python-for-machine-learning-beginners/?couponCode=78F44095E97F1832F47F
Traceback (most recent call last):
  File "<ipython-input-1-b8ef94d8895b>", line 567, in main1
    auto(remove_duplicates(links_ls))
  File "<ipython-input-1-b8ef94d8895b>", line 466, in auto
    purchased, amount = course_landing_api(course_id)
  File "<ipython-input-1-b8ef94d8895b>", line 309, in course_landing_api
    r = s.get(
NameError: name 's' is not defined

**Comment by cullzie** [comment]
Hey @adarsh-goel,
Looking at the code it is not from this project. Could you please confirm you are using the package: udemy-enroller
Thanks
